/*
 * crs_prodAB_mex.c
 *
 * Auxiliary code generation for function crs_prodAB
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "crs_prodAB.h"
#include "m2c.c"
#include "crs_prodAB.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void crs_prodAB_api(const mxArray ** prhs, const mxArray **plhs) {

    struct_T             A;
    struct_T             B;
    struct_T             C;
    mxArray              *_sub_mx1;

    /* Marshall in function inputs */

    if ( !mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument A has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[0])!=5)
        mexWarnMsgIdAndTxt("crs_prodAB:InputStructWrongFields",
            "Input argument A has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("crs_prodAB:WrongSizeOfInputArg",
            "Argument A must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[0], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument A does not have the field row_ptr.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument A.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&A.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.row_ptr, "A.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument A does not have the field col_ind.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument A.col_ind has incorrect data type. int32 is expected.");
    *(void**)&A.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.col_ind, "A.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument A does not have the field val.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument A.val has incorrect data type. double is expected.");
    *(void**)&A.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.val, "A.val", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument A does not have the field nrows.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument A.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAB:WrongSizeOfInputArg",
            "Argument A.nrows should be a scalar.");
    A.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[0], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument A does not have the field ncols.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument A.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAB:WrongSizeOfInputArg",
            "Argument A.ncols should be a scalar.");
    A.ncols = *(int32_T*)mxGetData(_sub_mx1);

    if ( !mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument B has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[1])!=5)
        mexWarnMsgIdAndTxt("crs_prodAB:InputStructWrongFields",
            "Input argument B has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("crs_prodAB:WrongSizeOfInputArg",
            "Argument B must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[1], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument B does not have the field row_ptr.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument B.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&B.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)B.row_ptr, "B.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[1], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument B does not have the field col_ind.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument B.col_ind has incorrect data type. int32 is expected.");
    *(void**)&B.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)B.col_ind, "B.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[1], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument B does not have the field val.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument B.val has incorrect data type. double is expected.");
    *(void**)&B.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)B.val, "B.val", 1);
    _sub_mx1 = mxGetField( prhs[1], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument B does not have the field nrows.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument B.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAB:WrongSizeOfInputArg",
            "Argument B.nrows should be a scalar.");
    B.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[1], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputStruct",
            "Input argument B does not have the field ncols.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAB:WrongInputType",
            "Input argument B.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAB:WrongSizeOfInputArg",
            "Argument B.ncols should be a scalar.");
    B.ncols = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    *(void **)&C.row_ptr = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)C.row_ptr, 1);
    *(void **)&C.col_ind = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)C.col_ind, 1);
    *(void **)&C.val = mxCalloc(1, sizeof(emxArray__common));    init_emxArray( (emxArray__common*)C.val, 1);

    /* Invoke the target function */
    crs_prodAB_initialize();
    crs_prodAB(&A, &B, &C);
    crs_prodAB_terminate();
    /* Marshall out function outputs */
    {const char *_fields[] = { "row_ptr", "col_ind", "val", "nrows", "ncols",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray( 1, &_one, 5, _fields);}
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)C.row_ptr, mxINT32_CLASS));
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)C.col_ind, mxINT32_CLASS));
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 2, move_emxArray_to_mxArray((emxArray__common*)C.val, mxDOUBLE_CLASS));
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 3, copy_scalar_to_mxArray(&C.nrows, mxINT32_CLASS));
    mxSetFieldByNumber( (mxArray*)(plhs[0]), 0, 4, copy_scalar_to_mxArray(&C.ncols, mxINT32_CLASS));    /* Free temporary variables */
    free_emxArray( (emxArray__common*)A.val); mxFree( A.val);
    free_emxArray( (emxArray__common*)A.col_ind); mxFree( A.col_ind);
    free_emxArray( (emxArray__common*)A.row_ptr); mxFree( A.row_ptr);

    free_emxArray( (emxArray__common*)B.val); mxFree( B.val);
    free_emxArray( (emxArray__common*)B.col_ind); mxFree( B.col_ind);
    free_emxArray( (emxArray__common*)B.row_ptr); mxFree( B.row_ptr);

    free_emxArray( (emxArray__common*)C.val); mxFree( C.val);
    free_emxArray( (emxArray__common*)C.col_ind); mxFree( C.col_ind);
    free_emxArray( (emxArray__common*)C.row_ptr); mxFree( C.row_ptr);
}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 2) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_prodAB:TooManyOutputArguments","Too many output arguments for entry-point 'crs_prodAB'.");
        /* Call the API function. */
        crs_prodAB_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("crs_prodAB:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'crs_prodAB'.");
}