/*
 * prodAtx_mex.c
 *
 * Auxiliary code generation for function prodAtx
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "prodAtx.h"
#include "m2c.c"
#include "prodAtx.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void prodAtx_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;

    int32_T              nthreads;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("prodAtx:WrongSizeOfInputArg",
            "Argument nthreads should be a scalar.");
    nthreads = *(int32_T*)mxGetData(prhs[3]);

    /* Invoke the target function */
    prodAtx_initialize();
    prodAtx(&A, &x, &b, nthreads);
    prodAtx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);}

void prodAtx_ser_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_ser:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_ser:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&b, 2);

    /* Invoke the target function */
    prodAtx_initialize();
    prodAtx_ser(&A, &x, &b);
    prodAtx_terminate();
    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);}

void prodAtx_ser1_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_ser1:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_ser1:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_ser1:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);

    /* Invoke the target function */
    prodAtx_initialize();
    prodAtx_ser1(&A, &x, &b);
    prodAtx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);}

void prodAtx_mpi_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_int32_T     nthreads;

    struct_T             comm;
    mxArray              *_sub_mx1;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[4]))
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[4])!=3)
        mexWarnMsgIdAndTxt("prodAtx_mpi:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[4], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("prodAtx_mpi:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Invoke the target function */
    prodAtx_initialize();
    prodAtx_mpi(&A, &x, &b, &nthreads, &comm);
    prodAtx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);
}

void prodAtx_mpip_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_int32_T     nthreads;
    emxArray_real_T      pbmsg;

    struct_T             comm;
    mxArray              *_sub_mx1;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 1);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[4]))
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[4])!=3)
        mexWarnMsgIdAndTxt("prodAtx_mpip:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[4], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetNumberOfElements(prhs[5]) && mxGetClassID(prhs[5]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip:WrongInputType",
            "Input argument pbmsg has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[5], (emxArray__common *)&pbmsg, "pbmsg", 2);

    /* Invoke the target function */
    prodAtx_initialize();
    prodAtx_mpip(&A, &x, &b, &nthreads, &comm, &pbmsg);
    prodAtx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);

    free_emxArray( (emxArray__common*)&pbmsg);}

void prodAtx_mpip1_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_int32_T     nthreads;
    emxArray_real_T      pbmsg;

    struct_T             comm;
    mxArray              *_sub_mx1;

    int32_T              pbsz;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[4]))
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[4])!=3)
        mexWarnMsgIdAndTxt("prodAtx_mpip1:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[4], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetNumberOfElements(prhs[5]) && mxGetClassID(prhs[5]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument pbmsg has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[5], (emxArray__common *)&pbmsg, "pbmsg", 2);
    if ( mxGetNumberOfElements(prhs[6]) && mxGetClassID(prhs[6]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongInputType",
            "Input argument pbsz has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[6]) != 1)
        mexErrMsgIdAndTxt("prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument pbsz should be a scalar.");
    pbsz = *(int32_T*)mxGetData(prhs[6]);

    /* Invoke the target function */
    prodAtx_initialize();
    prodAtx_mpip1(&A, &x, &b, &nthreads, &comm, &pbmsg, pbsz);
    prodAtx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);

    free_emxArray( (emxArray__common*)&pbmsg);}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 4) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtx:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtx'.");
        /* Call the API function. */
        prodAtx_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 2) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtx_ser:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtx_ser'.");
        /* Call the API function. */
        prodAtx_ser_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 3) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtx_ser1:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtx_ser1'.");
        /* Call the API function. */
        prodAtx_ser1_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 5) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtx_mpi:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtx_mpi'.");
        /* Call the API function. */
        prodAtx_mpi_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 6) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtx_mpip:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtx_mpip'.");
        /* Call the API function. */
        prodAtx_mpip_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 7) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtx_mpip1:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtx_mpip1'.");
        /* Call the API function. */
        prodAtx_mpip1_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("prodAtx:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'prodAtx'.");
}