/*
 * cuBCRSCreate_mex.c
 *
 * Auxiliary code for mexFunction of cuBCRSCreate
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {int32(0), int32(0), int32(0), int32(0), int32(0)} cuBCRSCreate_3args -args {int32(0), int32(0), int32(0)} cuBCRSCreate_4args -args {int32(0), int32(0), int32(0), int32(0)}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "cuBCRSCreate.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void cuBCRSCreate_api(const mxArray ** prhs, const mxArray **plhs) {

    MSP_CuBCRS           mat;
    mxArray              *_sub_mx1;

    int32_T              mb;
    int32_T              nb;
    int32_T              nnzb;
    int32_T              blkdim;
    int32_T              type;
    int32_T              *errCode;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongInputType",
            "Input argument mb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongSizeOfInputArg",
            "Argument mb should be a scalar.");
    mb = *(int32_T*)mxGetData(prhs[0]);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongInputType",
            "Input argument nb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongSizeOfInputArg",
            "Argument nb should be a scalar.");
    nb = *(int32_T*)mxGetData(prhs[1]);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongInputType",
            "Input argument nnzb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongSizeOfInputArg",
            "Argument nnzb should be a scalar.");
    nnzb = *(int32_T*)mxGetData(prhs[2]);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongInputType",
            "Input argument blkdim has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongSizeOfInputArg",
            "Argument blkdim should be a scalar.");
    blkdim = *(int32_T*)mxGetData(prhs[3]);
    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongInputType",
            "Input argument type has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongSizeOfInputArg",
            "Argument type should be a scalar.");
    type = *(int32_T*)mxGetData(prhs[4]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    cuBCRSCreate_initialize();

    cuBCRSCreate(mb, nb, nnzb, blkdim, type, &mat, errCode);

    cuBCRSCreate_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "rowptr", "colind", "vals", "type", "dimsb", "nnzb", "blkdim",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 7, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, copy_scalar_to_mxArray(&mat.rowptr, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, copy_scalar_to_mxArray(&mat.colind, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&mat.vals, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 3, copy_scalar_to_mxArray(&mat.type, mxINT32_CLASS));
    {int32_T _size[] = {1, 2};
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 4, copy_array_to_mxArray(mat.dimsb, mxINT32_CLASS, 2, _size)); }
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 5, copy_scalar_to_mxArray(&mat.nnzb, mxINT32_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 6, copy_scalar_to_mxArray(&mat.blkdim, mxINT32_CLASS));
    /* Nothing to do for plhs[1] */

}
void cuBCRSCreate_3args_api(const mxArray ** prhs, const mxArray **plhs) {

    MSP_CuBCRS           mat;
    mxArray              *_sub_mx1;

    int32_T              mb;
    int32_T              nb;
    int32_T              nnzb;
    int32_T              *errCode;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate_3args:WrongInputType",
            "Input argument mb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate_3args:WrongSizeOfInputArg",
            "Argument mb should be a scalar.");
    mb = *(int32_T*)mxGetData(prhs[0]);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate_3args:WrongInputType",
            "Input argument nb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate_3args:WrongSizeOfInputArg",
            "Argument nb should be a scalar.");
    nb = *(int32_T*)mxGetData(prhs[1]);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate_3args:WrongInputType",
            "Input argument nnzb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate_3args:WrongSizeOfInputArg",
            "Argument nnzb should be a scalar.");
    nnzb = *(int32_T*)mxGetData(prhs[2]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    cuBCRSCreate_initialize();

    cuBCRSCreate_3args(mb, nb, nnzb, &mat, errCode);

    cuBCRSCreate_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "rowptr", "colind", "vals", "type", "dimsb", "nnzb", "blkdim",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 7, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, copy_scalar_to_mxArray(&mat.rowptr, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, copy_scalar_to_mxArray(&mat.colind, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&mat.vals, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 3, copy_scalar_to_mxArray(&mat.type, mxINT32_CLASS));
    {int32_T _size[] = {1, 2};
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 4, copy_array_to_mxArray(mat.dimsb, mxINT32_CLASS, 2, _size)); }
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 5, copy_scalar_to_mxArray(&mat.nnzb, mxINT32_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 6, copy_scalar_to_mxArray(&mat.blkdim, mxINT32_CLASS));
    /* Nothing to do for plhs[1] */

}
void cuBCRSCreate_4args_api(const mxArray ** prhs, const mxArray **plhs) {

    MSP_CuBCRS           mat;
    mxArray              *_sub_mx1;

    int32_T              mb;
    int32_T              nb;
    int32_T              nnzb;
    int32_T              blkdim;
    int32_T              *errCode;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongInputType",
            "Input argument mb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongSizeOfInputArg",
            "Argument mb should be a scalar.");
    mb = *(int32_T*)mxGetData(prhs[0]);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongInputType",
            "Input argument nb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongSizeOfInputArg",
            "Argument nb should be a scalar.");
    nb = *(int32_T*)mxGetData(prhs[1]);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongInputType",
            "Input argument nnzb has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongSizeOfInputArg",
            "Argument nnzb should be a scalar.");
    nnzb = *(int32_T*)mxGetData(prhs[2]);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongInputType",
            "Input argument blkdim has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("cuBCRSCreate_4args:WrongSizeOfInputArg",
            "Argument blkdim should be a scalar.");
    blkdim = *(int32_T*)mxGetData(prhs[3]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }

    /* Invoke the target function */
    cuBCRSCreate_initialize();

    cuBCRSCreate_4args(mb, nb, nnzb, blkdim, &mat, errCode);

    cuBCRSCreate_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "rowptr", "colind", "vals", "type", "dimsb", "nnzb", "blkdim",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 7, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, copy_scalar_to_mxArray(&mat.rowptr, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, copy_scalar_to_mxArray(&mat.colind, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&mat.vals, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 3, copy_scalar_to_mxArray(&mat.type, mxINT32_CLASS));
    {int32_T _size[] = {1, 2};
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 4, copy_array_to_mxArray(mat.dimsb, mxINT32_CLASS, 2, _size)); }
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 5, copy_scalar_to_mxArray(&mat.nnzb, mxINT32_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 6, copy_scalar_to_mxArray(&mat.blkdim, mxINT32_CLASS));
    /* Nothing to do for plhs[1] */

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 5) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("cuBCRSCreate:TooManyOutputArguments","Too many output arguments for entry-point cuBCRSCreate.");
        /* Call the API function. */
        cuBCRSCreate_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 3) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("cuBCRSCreate_3args:TooManyOutputArguments","Too many output arguments for entry-point cuBCRSCreate_3args.");
        /* Call the API function. */
        cuBCRSCreate_3args_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 4) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("cuBCRSCreate_4args:TooManyOutputArguments","Too many output arguments for entry-point cuBCRSCreate_4args.");
        /* Call the API function. */
        cuBCRSCreate_4args_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("cuBCRSCreate:WrongNumberOfInputs","Incorrect number of input variables for entry-point cuBCRSCreate.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}