/*
 * cuBlasGetEnum_mex.c
 *
 * Auxiliary code for mexFunction of cuBlasGetEnum
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {m2c_string}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "cuBlasGetEnum.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void cuBlasGetEnum_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_char_T      str;

    int32_T              val;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("cuBlasGetEnum:WrongInputType",
            "Input argument str has incorrect data type. char is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&str, "str", 2);

    /* Preallocate output variables */

    /* Invoke the target function */
    cuBlasGetEnum_initialize();

    val = cuBlasGetEnum(&str);

    cuBlasGetEnum_terminate();

    /* Marshall out function outputs */
    plhs[0] = copy_scalar_to_mxArray(&val, mxINT32_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&str);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 1) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("cuBlasGetEnum:TooManyOutputArguments","Too many output arguments for entry-point cuBlasGetEnum.");
        /* Call the API function. */
        cuBlasGetEnum_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("cuBlasGetEnum:WrongNumberOfInputs","Incorrect number of input variables for entry-point cuBlasGetEnum.");
}