/*
 * cuVecCopySubFromGPU_mex.c
 *
 * Auxiliary code for mexFunction of cuVecCopySubFromGPU
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {m2c_int, CuVec, m2c_int, m2c_vec, m2c_int, m2c_int} cuVecCopySubFromGPU_async -args {m2c_int, CuVec, m2c_int, m2c_vec, m2c_int, m2c_int, CuStreamHandle}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "cuVecCopySubFromGPU.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void cuVecCopySubFromGPU_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      vec;

    struct0_T            cuVec;
    mxArray              *_sub_mx1;

    int32_T              n;
    int32_T              incCuVec;
    int32_T              istart;
    int32_T              inc;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument n has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument n should be a scalar.");
    n = *(int32_T*)mxGetData(prhs[0]);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument cuVec has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:InputStructWrongFields",
            "Input argument cuVec has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument cuVec must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputStruct",
            "Input argument cuVec does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT64_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument cuVec.data has incorrect data type. uint64 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument cuVec.data should be a scalar.");
    cuVec.data = *(uint64_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputStruct",
            "Input argument cuVec does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument cuVec.type has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument cuVec.type should be a scalar.");
    cuVec.type = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField(prhs[1], 0, "len");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputStruct",
            "Input argument cuVec does not have the field len.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument cuVec.len has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument cuVec.len should be a scalar.");
    cuVec.len = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument incCuVec has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument incCuVec should be a scalar.");
    incCuVec = *(int32_T*)mxGetData(prhs[2]);
    plhs[0] = mxDuplicateArray(prhs[3]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument vec has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&vec, "vec", 1);
    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument istart has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument istart should be a scalar.");
    istart = *(int32_T*)mxGetData(prhs[4]);
    if (mxGetNumberOfElements(prhs[5]) && mxGetClassID(prhs[5]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongInputType",
            "Input argument inc has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongSizeOfInputArg",
            "Argument inc should be a scalar.");
    inc = *(int32_T*)mxGetData(prhs[5]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    cuVecCopySubFromGPU_initialize();

    cuVecCopySubFromGPU(n, &cuVec, incCuVec, &vec, istart, inc, errCode, toplevel);

    cuVecCopySubFromGPU_terminate();

    /* Marshall out function outputs */
    if (vec.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&vec, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&vec);
}
void cuVecCopySubFromGPU_async_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      vec;

    struct0_T            cuVec;
    struct1_T            strm;
    mxArray              *_sub_mx1;

    int32_T              n;
    int32_T              incCuVec;
    int32_T              istart;
    int32_T              inc;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument n has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument n should be a scalar.");
    n = *(int32_T*)mxGetData(prhs[0]);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument cuVec has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:InputStructWrongFields",
            "Input argument cuVec has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument cuVec must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputStruct",
            "Input argument cuVec does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT64_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument cuVec.data has incorrect data type. uint64 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument cuVec.data should be a scalar.");
    cuVec.data = *(uint64_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputStruct",
            "Input argument cuVec does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument cuVec.type has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument cuVec.type should be a scalar.");
    cuVec.type = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField(prhs[1], 0, "len");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputStruct",
            "Input argument cuVec does not have the field len.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument cuVec.len has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument cuVec.len should be a scalar.");
    cuVec.len = *(int32_T*)mxGetData(_sub_mx1);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument incCuVec has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument incCuVec should be a scalar.");
    incCuVec = *(int32_T*)mxGetData(prhs[2]);
    plhs[0] = mxDuplicateArray(prhs[3]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument vec has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&vec, "vec", 1);
    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument istart has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument istart should be a scalar.");
    istart = *(int32_T*)mxGetData(prhs[4]);
    if (mxGetNumberOfElements(prhs[5]) && mxGetClassID(prhs[5]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument inc has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument inc should be a scalar.");
    inc = *(int32_T*)mxGetData(prhs[5]);

    if (!mxIsStruct(prhs[6]))
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument strm has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[6])!=3)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:InputStructWrongFields",
            "Input argument strm has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[6]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument strm must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[6], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputStruct",
            "Input argument strm does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument strm.data has incorrect data type. uint8 is expected.");
    *(void**)&strm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)strm.data, "strm.data", 1);
    _sub_mx1 = mxGetField(prhs[6], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputStruct",
            "Input argument strm does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument strm.type has incorrect data type. char is expected.");
    *(void**)&strm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)strm.type, "strm.type", 2);
    _sub_mx1 = mxGetField(prhs[6], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputStruct",
            "Input argument strm does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongInputType",
            "Input argument strm.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:WrongSizeOfInputArg",
            "Argument strm.nitems should be a scalar.");
    strm.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    cuVecCopySubFromGPU_initialize();

    cuVecCopySubFromGPU_async(n, &cuVec, incCuVec, &vec, istart, inc, &strm, errCode, toplevel);

    cuVecCopySubFromGPU_terminate();

    /* Marshall out function outputs */
    if (vec.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&vec, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&vec);
    free_emxArray((emxArray__common*)strm.type); mxFree(strm.type);
    free_emxArray((emxArray__common*)strm.data); mxFree(strm.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 6) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("cuVecCopySubFromGPU:TooManyOutputArguments","Too many output arguments for entry-point cuVecCopySubFromGPU.");
        /* Call the API function. */
        cuVecCopySubFromGPU_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 7) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("cuVecCopySubFromGPU_async:TooManyOutputArguments","Too many output arguments for entry-point cuVecCopySubFromGPU_async.");
        /* Call the API function. */
        cuVecCopySubFromGPU_async_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("cuVecCopySubFromGPU:WrongNumberOfInputs","Incorrect number of input variables for entry-point cuVecCopySubFromGPU.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}