/*
 * sqnormf_mex.c
 *
 * Auxiliary code generation for function sqnormf
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "sqnormf.h"
#include "m2c.c"
#include "sqnormf.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void sqnormf_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_int32_T     nthreads;

    real_T               *sqnrm;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    plhs[0] = mxDuplicateArray( prhs[1]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf:WrongInputType",
            "Input argument sqnrm has incorrect data type. double is expected.");
    if ( mxGetNumberOfElements(plhs[0]) != 1)
        mexErrMsgIdAndTxt("sqnormf:WrongSizeOfInputArg",
            "Argument sqnrm should be a scalar.");
    sqnrm = (real_T*)mxGetData(plhs[0]);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("sqnormf:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&nthreads, "nthreads", 1);

    /* Invoke the target function */
    sqnormf_initialize();
    sqnormf(&A, sqnrm, &nthreads);
    sqnormf_terminate();
    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&nthreads);}

void sqnormf_ser_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;

    real_T               s;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf_ser:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);

    /* Preallocate output variables */

    /* Invoke the target function */
    sqnormf_initialize();
    s = sqnormf_ser(&A);
    sqnormf_terminate();
    /* Marshall out function outputs */
    plhs[0] = copy_scalar_to_mxArray(&s, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);}

void sqnormf_mpi_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_int32_T     nthreads;

    struct_T             comm;
    mxArray              *_sub_mx1;

    real_T               *s;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    plhs[0] = mxDuplicateArray( prhs[1]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputType",
            "Input argument s has incorrect data type. double is expected.");
    if ( mxGetNumberOfElements(plhs[0]) != 1)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongSizeOfInputArg",
            "Argument s should be a scalar.");
    s = (real_T*)mxGetData(plhs[0]);
    if ( mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[3]))
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[3])!=3)
        mexWarnMsgIdAndTxt("sqnormf_mpi:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[3], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[3], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[3], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("sqnormf_mpi:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Invoke the target function */
    sqnormf_initialize();
    sqnormf_mpi(&A, s, &nthreads, &comm);
    sqnormf_terminate();
    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);
}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 3) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("sqnormf:TooManyOutputArguments","Too many output arguments for entry-point 'sqnormf'.");
        /* Call the API function. */
        sqnormf_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 1) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("sqnormf_ser:TooManyOutputArguments","Too many output arguments for entry-point 'sqnormf_ser'.");
        /* Call the API function. */
        sqnormf_ser_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 4) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("sqnormf_mpi:TooManyOutputArguments","Too many output arguments for entry-point 'sqnormf_mpi'.");
        /* Call the API function. */
        sqnormf_mpi_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("sqnormf:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'sqnormf'.");
}