/*
 * cudaVecCopyToHost_mex.c
 *
 * Auxiliary code for mexFunction of cudaVecCopyToHost
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {CudaVec, m2c_vec}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "cudaVecCopyToHost.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void cudaVecCopyToHost_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      vec;

    struct0_T            cuVec;
    mxArray              *_sub_mx1;

    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */

    if (!mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputType",
            "Input argument cuVec has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[0])!=3)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:InputStructWrongFields",
            "Input argument cuVec has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongSizeOfInputArg",
            "Argument cuVec must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[0], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputStruct",
            "Input argument cuVec does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT32_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputType",
            "Input argument cuVec.data has incorrect data type. uint32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 2)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongSizeOfInputArg",
            "Argument cuVec.data must contain 2 numbers.");
    copy_mxArray_to_array(_sub_mx1, cuVec.data, 2);
    _sub_mx1 = mxGetField(prhs[0], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputStruct",
            "Input argument cuVec does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputType",
            "Input argument cuVec.type has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongSizeOfInputArg",
            "Argument cuVec.type should be a scalar.");
    cuVec.type = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField(prhs[0], 0, "len");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputStruct",
            "Input argument cuVec does not have the field len.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputType",
            "Input argument cuVec.len has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongSizeOfInputArg",
            "Argument cuVec.len should be a scalar.");
    cuVec.len = *(int32_T*)mxGetData(_sub_mx1);
    plhs[0] = mxDuplicateArray(prhs[1]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongInputType",
            "Input argument vec has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&vec, "vec", 1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    cudaVecCopyToHost_initialize();

    cudaVecCopyToHost(&cuVec, &vec, errCode, toplevel);

    cudaVecCopyToHost_terminate();

    /* Marshall out function outputs */
    if (vec.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&vec, mxDOUBLE_CLASS);
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&vec);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 2) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("cudaVecCopyToHost:TooManyOutputArguments","Too many output arguments for entry-point cudaVecCopyToHost.");
        /* Call the API function. */
        cudaVecCopyToHost_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("cudaVecCopyToHost:WrongNumberOfInputs","Incorrect number of input variables for entry-point cudaVecCopyToHost.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}