/*
 * prodAtAx_mex.c
 *
 * Auxiliary code generation for function prodAtAx
 *
 * C source code generated by m2c.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "prodAtAx.h"
#include "m2c.c"
#include "prodAtAx.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void prodAtAx_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_real_T      Ax;
    emxArray_int32_T     nthreads;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    plhs[1] = mxDuplicateArray( prhs[3]);
    if ( mxGetNumberOfElements(plhs[1]) && mxGetClassID(plhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument Ax has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[1], (emxArray__common *)&Ax, "Ax", 2);
    if ( mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[4], (emxArray__common *)&nthreads, "nthreads", 1);

    /* Invoke the target function */
    prodAtAx_initialize();
    prodAtAx(&A, &x, &b, &Ax, &nthreads);
    prodAtAx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);
    if (Ax.canFreeData) plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&Ax, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&Ax);
    free_emxArray( (emxArray__common*)&nthreads);}

void prodAtAx_ser_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&b, 2);

    /* Invoke the target function */
    prodAtAx_initialize();
    prodAtAx_ser(&A, &x, &b);
    prodAtAx_terminate();
    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);}

void prodAtAx_ser1_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser1:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser1:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser1:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);

    /* Invoke the target function */
    prodAtAx_initialize();
    prodAtAx_ser1(&A, &x, &b);
    prodAtAx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);}

void prodAtAx_mpi_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_real_T      Ax;
    emxArray_int32_T     nthreads;

    struct_T             comm;
    mxArray              *_sub_mx1;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    plhs[1] = mxDuplicateArray( prhs[3]);
    if ( mxGetNumberOfElements(plhs[1]) && mxGetClassID(plhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument Ax has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[1], (emxArray__common *)&Ax, "Ax", 2);
    if ( mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[4], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[5]))
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[5])!=3)
        mexWarnMsgIdAndTxt("prodAtAx_mpi:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[5], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[5], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[5], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("prodAtAx_mpi:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Invoke the target function */
    prodAtAx_initialize();
    prodAtAx_mpi(&A, &x, &b, &Ax, &nthreads, &comm);
    prodAtAx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);
    if (Ax.canFreeData) plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&Ax, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&Ax);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);
}

void prodAtAx_mpip_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_real_T      Ax;
    emxArray_int32_T     nthreads;
    emxArray_real_T      pbmsg;

    struct_T             comm;
    mxArray              *_sub_mx1;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    plhs[1] = mxDuplicateArray( prhs[3]);
    if ( mxGetNumberOfElements(plhs[1]) && mxGetClassID(plhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument Ax has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[1], (emxArray__common *)&Ax, "Ax", 2);
    if ( mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[4], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[5]))
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[5])!=3)
        mexWarnMsgIdAndTxt("prodAtAx_mpip:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[5], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[5], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[5], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetNumberOfElements(prhs[6]) && mxGetClassID(prhs[6]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip:WrongInputType",
            "Input argument pbmsg has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[6], (emxArray__common *)&pbmsg, "pbmsg", 2);

    /* Invoke the target function */
    prodAtAx_initialize();
    prodAtAx_mpip(&A, &x, &b, &Ax, &nthreads, &comm, &pbmsg);
    prodAtAx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);
    if (Ax.canFreeData) plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&Ax, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&Ax);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);

    free_emxArray( (emxArray__common*)&pbmsg);}

void prodAtAx_mpip1_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_real_T      Ax;
    emxArray_int32_T     nthreads;
    emxArray_real_T      pbmsg;

    struct_T             comm;
    mxArray              *_sub_mx1;

    int32_T              pbsz;

    /* Marshall in function inputs */
    if ( mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if ( mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    plhs[1] = mxDuplicateArray( prhs[3]);
    if ( mxGetNumberOfElements(plhs[1]) && mxGetClassID(plhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument Ax has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[1], (emxArray__common *)&Ax, "Ax", 2);
    if ( mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[4], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[5]))
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[5])!=3)
        mexWarnMsgIdAndTxt("prodAtAx_mpip1:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[5], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[5], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[5], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetNumberOfElements(prhs[6]) && mxGetClassID(prhs[6]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument pbmsg has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[6], (emxArray__common *)&pbmsg, "pbmsg", 2);
    if ( mxGetNumberOfElements(prhs[7]) && mxGetClassID(prhs[7]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongInputType",
            "Input argument pbsz has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[7]) != 1)
        mexErrMsgIdAndTxt("prodAtAx_mpip1:WrongSizeOfInputArg",
            "Argument pbsz should be a scalar.");
    pbsz = *(int32_T*)mxGetData(prhs[7]);

    /* Invoke the target function */
    prodAtAx_initialize();
    prodAtAx_mpip1(&A, &x, &b, &Ax, &nthreads, &comm, &pbmsg, pbsz);
    prodAtAx_terminate();
    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);
    if (Ax.canFreeData) plhs[3] = move_emxArray_to_mxArray((emxArray__common*)&Ax, mxDOUBLE_CLASS);    /* Free temporary variables */
    free_emxArray( (emxArray__common*)&A);
    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&Ax);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);

    free_emxArray( (emxArray__common*)&pbmsg);}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);
    if (nrhs == 5) {
         if (nlhs > 2)
            mexErrMsgIdAndTxt("prodAtAx:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtAx'.");
        /* Call the API function. */
    prodAtAx_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 2) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtAx_ser:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtAx_ser'.");
        /* Call the API function. */
    prodAtAx_ser_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 3) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtAx_ser1:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtAx_ser1'.");
        /* Call the API function. */
    prodAtAx_ser1_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 6) {
         if (nlhs > 2)
            mexErrMsgIdAndTxt("prodAtAx_mpi:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtAx_mpi'.");
        /* Call the API function. */
    prodAtAx_mpi_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 7) {
         if (nlhs > 2)
            mexErrMsgIdAndTxt("prodAtAx_mpip:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtAx_mpip'.");
        /* Call the API function. */
    prodAtAx_mpip_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 8) {
         if (nlhs > 2)
            mexErrMsgIdAndTxt("prodAtAx_mpip1:TooManyOutputArguments","Too many output arguments for entry-point 'prodAtAx_mpip1'.");
        /* Call the API function. */
    prodAtAx_mpip1_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("prodAtAx:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'prodAtAx'.");
    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}