/*
 * codegen/lib/prodAtAx/prodAtAx_mex.c
 *
 * Auxiliary code for mexFunction of prodAtAx
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof(int32(0),[1,1],[1,0])} prodAtAx_ser -args {coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf])} prodAtAx_ser1 -args {coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf])}  enableInline=1 withOMP=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "prodAtAx.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void prodAtAx_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_real_T      Ax;
    emxArray_int32_T     nthreads;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray(prhs[2]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    plhs[1] = mxDuplicateArray(prhs[3]);
    if (mxGetNumberOfElements(plhs[1]) && mxGetClassID(plhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument Ax has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[1], (emxArray__common *)&Ax, "Ax", 2);
    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("prodAtAx:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[4], (emxArray__common *)&nthreads, "nthreads", 1);

    /* Invoke the target function */
    prodAtAx_initialize();

    prodAtAx(&A, &x, &b, &Ax, &nthreads);

    prodAtAx_terminate();

    /* Marshall out function outputs */
    if (b.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);
    if (Ax.canFreeData) plhs[1] = move_emxArray_to_mxArray((emxArray__common*)&Ax, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&A);
    free_emxArray((emxArray__common*)&x);
    free_emxArray((emxArray__common*)&b);
    free_emxArray((emxArray__common*)&Ax);
    free_emxArray((emxArray__common*)&nthreads);
}
void prodAtAx_ser_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&b, 2);

    /* Invoke the target function */
    prodAtAx_initialize();

    prodAtAx_ser(&A, &x, &b);

    prodAtAx_terminate();

    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&A);
    free_emxArray((emxArray__common*)&x);
    free_emxArray((emxArray__common*)&b);
}
void prodAtAx_ser1_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_real_T      x;
    emxArray_real_T      b;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser1:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser1:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray(prhs[2]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("prodAtAx_ser1:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);

    /* Invoke the target function */
    prodAtAx_initialize();

    prodAtAx_ser1(&A, &x, &b);

    prodAtAx_terminate();

    /* Marshall out function outputs */
    if (b.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&A);
    free_emxArray((emxArray__common*)&x);
    free_emxArray((emxArray__common*)&b);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 5) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("prodAtAx:TooManyOutputArguments","Too many output arguments for entry-point prodAtAx.");
        /* Call the API function. */
        prodAtAx_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 2) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtAx_ser:TooManyOutputArguments","Too many output arguments for entry-point prodAtAx_ser.");
        /* Call the API function. */
        prodAtAx_ser_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 3) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("prodAtAx_ser1:TooManyOutputArguments","Too many output arguments for entry-point prodAtAx_ser1.");
        /* Call the API function. */
        prodAtAx_ser1_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("prodAtAx:WrongNumberOfInputs","Incorrect number of input variables for entry-point prodAtAx.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}