/*
 * cudaVecCopyFromHost_mex.c
 *
 * Auxiliary code for mexFunction of cudaVecCopyFromHost
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {m2c_vec, CudaVec}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "cudaVecCopyFromHost.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void cudaVecCopyFromHost_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      vec;

    struct0_T            cuVec;
    mxArray              *_sub_mx1;

    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputType",
            "Input argument vec has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&vec, "vec", 1);

    if (!mxIsStruct(prhs[1]))
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputType",
            "Input argument cuVec has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[1])!=3)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:InputStructWrongFields",
            "Input argument cuVec has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongSizeOfInputArg",
            "Argument cuVec must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[1], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputStruct",
            "Input argument cuVec does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT32_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputType",
            "Input argument cuVec.data has incorrect data type. uint32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 2)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongSizeOfInputArg",
            "Argument cuVec.data must contain 2 numbers.");
    copy_mxArray_to_array(_sub_mx1, cuVec.data, 2);
    _sub_mx1 = mxGetField(prhs[1], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputStruct",
            "Input argument cuVec does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputType",
            "Input argument cuVec.type has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongSizeOfInputArg",
            "Argument cuVec.type should be a scalar.");
    cuVec.type = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField(prhs[1], 0, "len");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputStruct",
            "Input argument cuVec does not have the field len.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongInputType",
            "Input argument cuVec.len has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongSizeOfInputArg",
            "Argument cuVec.len should be a scalar.");
    cuVec.len = *(int32_T*)mxGetData(_sub_mx1);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[0], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[1], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    cudaVecCopyFromHost_initialize();

    cudaVecCopyFromHost(&vec, &cuVec, errCode, toplevel);

    cudaVecCopyFromHost_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */
    /* Nothing to do for plhs[1] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&vec);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 2) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("cudaVecCopyFromHost:TooManyOutputArguments","Too many output arguments for entry-point cudaVecCopyFromHost.");
        /* Call the API function. */
        cudaVecCopyFromHost_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("cudaVecCopyFromHost:WrongNumberOfInputs","Incorrect number of input variables for entry-point cudaVecCopyFromHost.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}