/*
 * codegen/lib/sqnormf/sqnormf_mex.c
 *
 * Auxiliary code for mexFunction of sqnormf
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {coder.typeof(0, [inf,inf]), 0, coder.typeof(int32(0), [1,1], [1,0])} sqnormf_ser -args {coder.typeof(0, [inf,inf])}  enableInline=1 withOMP=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "sqnormf.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void sqnormf_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;
    emxArray_int32_T     nthreads;

    real64_T             *sqnrm;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);
    plhs[0] = mxDuplicateArray(prhs[1]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf:WrongInputType",
            "Input argument sqnrm has incorrect data type. double is expected.");
    if (mxGetNumberOfElements(plhs[0]) != 1)
        mexErrMsgIdAndTxt("sqnormf:WrongSizeOfInputArg",
            "Argument sqnrm should be a scalar.");
    sqnrm = (real64_T*)mxGetData(plhs[0]);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("sqnormf:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)&nthreads, "nthreads", 1);

    /* Invoke the target function */
    sqnormf_initialize();

    sqnormf(&A, sqnrm, &nthreads);

    sqnormf_terminate();

    /* Marshall out function outputs */
    /* Nothing to do for plhs[0] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&A);
    free_emxArray((emxArray__common*)&nthreads);
}
void sqnormf_ser_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      A;

    real64_T             s;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("sqnormf_ser:WrongInputType",
            "Input argument A has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&A, "A", 2);

    /* Preallocate output variables */

    /* Invoke the target function */
    sqnormf_initialize();

    s = sqnormf_ser(&A);

    sqnormf_terminate();

    /* Marshall out function outputs */
    plhs[0] = copy_scalar_to_mxArray(&s, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&A);
}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 3) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("sqnormf:TooManyOutputArguments","Too many output arguments for entry-point sqnormf.");
        /* Call the API function. */
        sqnormf_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 1) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("sqnormf_ser:TooManyOutputArguments","Too many output arguments for entry-point sqnormf_ser.");
        /* Call the API function. */
        sqnormf_ser_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("sqnormf:WrongNumberOfInputs","Incorrect number of input variables for entry-point sqnormf.");
}