/*
 * codegen/lib/dotprod/dotprod_mex.c
 *
 * Auxiliary code for mexFunction of dotprod
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof( int32(1), [1,1], [1,0])} dotprod_ser -args {coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf])} dotprod_mpi -args {coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof(0, [inf,inf]), coder.typeof( int32(1), [1,1], [1,0]), MPI_Comm}  enableInline=1 withOMP=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "dotprod.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void dotprod_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      u;
    emxArray_real_T      v;
    emxArray_real_T      prod;
    emxArray_int32_T     nthreads;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod:WrongInputType",
            "Input argument u has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&u, "u", 2);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod:WrongInputType",
            "Input argument v has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&v, "v", 2);
    plhs[0] = mxDuplicateArray(prhs[2]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod:WrongInputType",
            "Input argument prod has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&prod, "prod", 2);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("dotprod:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    /* Invoke the target function */
    dotprod_initialize();

    dotprod(&u, &v, &prod, &nthreads);

    dotprod_terminate();

    /* Marshall out function outputs */
    if (prod.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&prod, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&u);
    free_emxArray((emxArray__common*)&v);
    free_emxArray((emxArray__common*)&prod);
    free_emxArray((emxArray__common*)&nthreads);
}
void dotprod_ser_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      u;
    emxArray_real_T      v;
    emxArray_real_T      prod;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod_ser:WrongInputType",
            "Input argument u has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&u, "u", 2);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod_ser:WrongInputType",
            "Input argument v has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&v, "v", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&prod, 2);

    /* Invoke the target function */
    dotprod_initialize();

    dotprod_ser(&u, &v, &prod);

    dotprod_terminate();

    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&prod, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&u);
    free_emxArray((emxArray__common*)&v);
    free_emxArray((emxArray__common*)&prod);
}
void dotprod_mpi_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      u;
    emxArray_real_T      v;
    emxArray_real_T      prod;
    emxArray_int32_T     n;

    struct0_T            comm;
    mxArray              *_sub_mx1;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument u has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)&u, "u", 2);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument v has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&v, "v", 2);
    plhs[0] = mxDuplicateArray(prhs[2]);
    if (mxGetNumberOfElements(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument prod has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&prod, "prod", 2);
    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument n has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&n, "n", 1);

    if (!mxIsStruct(prhs[4]))
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if (mxGetNumberOfFields(prhs[4])!=3)
        mexErrMsgIdAndTxt("dotprod_mpi:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField(prhs[4], 0, "data");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 1);
    _sub_mx1 = mxGetField(prhs[4], 0, "type");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField(prhs[4], 0, "nitems");
    if (_sub_mx1==NULL)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if (mxGetNumberOfElements(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("dotprod_mpi:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Invoke the target function */
    dotprod_initialize();

    dotprod_mpi(&u, &v, &prod, &n, &comm);

    dotprod_terminate();

    /* Marshall out function outputs */
    if (prod.canFreeData) plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&prod, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray((emxArray__common*)&u);
    free_emxArray((emxArray__common*)&v);
    free_emxArray((emxArray__common*)&prod);
    free_emxArray((emxArray__common*)&n);
    free_emxArray((emxArray__common*)comm.type); mxFree(comm.type);
    free_emxArray((emxArray__common*)comm.data); mxFree(comm.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 4) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("dotprod:TooManyOutputArguments","Too many output arguments for entry-point dotprod.");
        /* Call the API function. */
        dotprod_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 2) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("dotprod_ser:TooManyOutputArguments","Too many output arguments for entry-point dotprod_ser.");
        /* Call the API function. */
        dotprod_ser_api(prhs, (const mxArray**)plhs);
    }
    else if (nrhs == 5) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("dotprod_mpi:TooManyOutputArguments","Too many output arguments for entry-point dotprod_mpi.");
        /* Call the API function. */
        dotprod_mpi_api(prhs, (const mxArray**)plhs);
    }
    else
        mexErrMsgIdAndTxt("dotprod:WrongNumberOfInputs","Incorrect number of input variables for entry-point dotprod.");
}