/*
 * cuStreamCreate_mex.c
 *
 * Auxiliary code for mexFunction of cuStreamCreate
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "cuStreamCreate.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void cuStreamCreate_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            stm;
    mxArray              *_sub_mx1;

    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Preallocate output variables */
    *(void **)&stm.data = mxCalloc(1, sizeof(emxArray__common));    init_emxArray((emxArray__common*)stm.data, 1);
    *(void **)&stm.type = mxCalloc(1, sizeof(emxArray__common));    init_emxArray((emxArray__common*)stm.type, 2);
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    cuStreamCreate_initialize();

    cuStreamCreate(&stm, errCode, toplevel);

    cuStreamCreate_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "data", "type", "nitems",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 3, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, move_emxArray_to_mxArray((emxArray__common*)stm.data, mxUINT8_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)stm.type, mxCHAR_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_scalar_to_mxArray(&stm.nitems, mxINT32_CLASS));
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)stm.type); mxFree(stm.type);
    free_emxArray((emxArray__common*)stm.data); mxFree(stm.data);

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 0) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("cuStreamCreate:TooManyOutputArguments","Too many output arguments for entry-point cuStreamCreate.");
        /* Call the API function. */
        cuStreamCreate_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("cuStreamCreate:WrongNumberOfInputs","Incorrect number of input variables for entry-point cuStreamCreate.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}