/*
 * crs_prodAtx_mex.c
 *
 * Auxiliary code generation for function crs_prodAtx
 *
 * C source code generated by lib2mex.
*
 */

#include "mex.h"

#define BUILD_MEX
/* Include the C file generated by codegen in lib mode */
#include "crs_prodAtx.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


void crs_prodAtx_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_int32_T     nthreads;

    struct_T             A;
    mxArray              *_sub_mx1;


    /* Marshall in function inputs */

    if ( !mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument A has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[0])!=5)
        mexWarnMsgIdAndTxt("crs_prodAtx:InputStructWrongFields",
            "Input argument A has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongSizeOfInputArg",
            "Argument A must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[0], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputStruct",
            "Input argument A does not have the field row_ptr.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument A.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&A.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.row_ptr, "A.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputStruct",
            "Input argument A does not have the field col_ind.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument A.col_ind has incorrect data type. int32 is expected.");
    *(void**)&A.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.col_ind, "A.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputStruct",
            "Input argument A does not have the field val.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument A.val has incorrect data type. double is expected.");
    *(void**)&A.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.val, "A.val", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputStruct",
            "Input argument A does not have the field nrows.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument A.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongSizeOfInputArg",
            "Argument A.nrows should be a scalar.");
    A.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[0], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputStruct",
            "Input argument A does not have the field ncols.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument A.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongSizeOfInputArg",
            "Argument A.ncols should be a scalar.");
    A.ncols = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetData(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetData(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    /* Invoke the target function */
    crs_prodAtx_initialize();
    crs_prodAtx(&A, &x, &b, &nthreads);
    crs_prodAtx_terminate();

    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray( (emxArray__common*)A.val); mxFree( A.val);
    free_emxArray( (emxArray__common*)A.col_ind); mxFree( A.col_ind);
    free_emxArray( (emxArray__common*)A.row_ptr); mxFree( A.row_ptr);

    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&nthreads);
}


void crs_prodAtx_ser_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      x;
    emxArray_real_T      b;

    struct_T             A;
    mxArray              *_sub_mx1;


    /* Marshall in function inputs */

    if ( !mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputType",
            "Input argument A has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[0])!=5)
        mexWarnMsgIdAndTxt("crs_prodAtx_ser:InputStructWrongFields",
            "Input argument A has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongSizeOfInputArg",
            "Argument A must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[0], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputStruct",
            "Input argument A does not have the field row_ptr.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputType",
            "Input argument A.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&A.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.row_ptr, "A.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputStruct",
            "Input argument A does not have the field col_ind.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputType",
            "Input argument A.col_ind has incorrect data type. int32 is expected.");
    *(void**)&A.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.col_ind, "A.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputStruct",
            "Input argument A does not have the field val.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputType",
            "Input argument A.val has incorrect data type. double is expected.");
    *(void**)&A.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.val, "A.val", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputStruct",
            "Input argument A does not have the field nrows.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputType",
            "Input argument A.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongSizeOfInputArg",
            "Argument A.nrows should be a scalar.");
    A.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[0], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputStruct",
            "Input argument A does not have the field ncols.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputType",
            "Input argument A.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongSizeOfInputArg",
            "Argument A.ncols should be a scalar.");
    A.ncols = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);

    /* Preallocate output variables */
    init_emxArray((emxArray__common*)&b, 2);

    /* Invoke the target function */
    crs_prodAtx_initialize();
    crs_prodAtx_ser(&A, &x, &b);
    crs_prodAtx_terminate();

    /* Marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray( (emxArray__common*)A.val); mxFree( A.val);
    free_emxArray( (emxArray__common*)A.col_ind); mxFree( A.col_ind);
    free_emxArray( (emxArray__common*)A.row_ptr); mxFree( A.row_ptr);

    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
}


void crs_prodAtx_ser1_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      x;
    emxArray_real_T      b;

    struct_T             A;
    mxArray              *_sub_mx1;


    /* Marshall in function inputs */

    if ( !mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument A has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[0])!=5)
        mexWarnMsgIdAndTxt("crs_prodAtx_ser1:InputStructWrongFields",
            "Input argument A has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongSizeOfInputArg",
            "Argument A must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[0], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputStruct",
            "Input argument A does not have the field row_ptr.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument A.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&A.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.row_ptr, "A.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputStruct",
            "Input argument A does not have the field col_ind.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument A.col_ind has incorrect data type. int32 is expected.");
    *(void**)&A.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.col_ind, "A.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputStruct",
            "Input argument A does not have the field val.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument A.val has incorrect data type. double is expected.");
    *(void**)&A.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.val, "A.val", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputStruct",
            "Input argument A does not have the field nrows.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument A.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongSizeOfInputArg",
            "Argument A.nrows should be a scalar.");
    A.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[0], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputStruct",
            "Input argument A does not have the field ncols.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument A.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongSizeOfInputArg",
            "Argument A.ncols should be a scalar.");
    A.ncols = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetData(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_ser1:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);

    /* Invoke the target function */
    crs_prodAtx_initialize();
    crs_prodAtx_ser1(&A, &x, &b);
    crs_prodAtx_terminate();

    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray( (emxArray__common*)A.val); mxFree( A.val);
    free_emxArray( (emxArray__common*)A.col_ind); mxFree( A.col_ind);
    free_emxArray( (emxArray__common*)A.row_ptr); mxFree( A.row_ptr);

    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
}


void crs_prodAtx_mpi_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_int32_T     nthreads;

    struct_T             A;
    b_struct_T           comm;
    mxArray              *_sub_mx1;


    /* Marshall in function inputs */

    if ( !mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument A has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[0])!=5)
        mexWarnMsgIdAndTxt("crs_prodAtx_mpi:InputStructWrongFields",
            "Input argument A has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongSizeOfInputArg",
            "Argument A must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[0], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument A does not have the field row_ptr.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument A.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&A.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.row_ptr, "A.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument A does not have the field col_ind.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument A.col_ind has incorrect data type. int32 is expected.");
    *(void**)&A.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.col_ind, "A.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument A does not have the field val.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument A.val has incorrect data type. double is expected.");
    *(void**)&A.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.val, "A.val", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument A does not have the field nrows.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument A.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongSizeOfInputArg",
            "Argument A.nrows should be a scalar.");
    A.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[0], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument A does not have the field ncols.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument A.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongSizeOfInputArg",
            "Argument A.ncols should be a scalar.");
    A.ncols = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetData(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetData(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[4]))
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[4])!=3)
        mexWarnMsgIdAndTxt("crs_prodAtx_mpi:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[4], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpi:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);

    /* Invoke the target function */
    crs_prodAtx_initialize();
    crs_prodAtx_mpi(&A, &x, &b, &nthreads, &comm);
    crs_prodAtx_terminate();

    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray( (emxArray__common*)A.val); mxFree( A.val);
    free_emxArray( (emxArray__common*)A.col_ind); mxFree( A.col_ind);
    free_emxArray( (emxArray__common*)A.row_ptr); mxFree( A.row_ptr);

    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);

}


void crs_prodAtx_mpip_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_int32_T     nthreads;
    emxArray_real_T      pbmsg;

    struct_T             A;
    b_struct_T           comm;
    mxArray              *_sub_mx1;


    /* Marshall in function inputs */

    if ( !mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument A has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[0])!=5)
        mexWarnMsgIdAndTxt("crs_prodAtx_mpip:InputStructWrongFields",
            "Input argument A has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongSizeOfInputArg",
            "Argument A must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[0], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument A does not have the field row_ptr.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument A.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&A.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.row_ptr, "A.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument A does not have the field col_ind.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument A.col_ind has incorrect data type. int32 is expected.");
    *(void**)&A.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.col_ind, "A.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument A does not have the field val.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument A.val has incorrect data type. double is expected.");
    *(void**)&A.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.val, "A.val", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument A does not have the field nrows.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument A.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongSizeOfInputArg",
            "Argument A.nrows should be a scalar.");
    A.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[0], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument A does not have the field ncols.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument A.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongSizeOfInputArg",
            "Argument A.ncols should be a scalar.");
    A.ncols = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetData(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetData(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[4]))
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[4])!=3)
        mexWarnMsgIdAndTxt("crs_prodAtx_mpip:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[4], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[5]) && mxGetClassID(prhs[5]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip:WrongInputType",
            "Input argument pbmsg has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[5], (emxArray__common *)&pbmsg, "pbmsg", 1);

    /* Invoke the target function */
    crs_prodAtx_initialize();
    crs_prodAtx_mpip(&A, &x, &b, &nthreads, &comm, &pbmsg);
    crs_prodAtx_terminate();

    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray( (emxArray__common*)A.val); mxFree( A.val);
    free_emxArray( (emxArray__common*)A.col_ind); mxFree( A.col_ind);
    free_emxArray( (emxArray__common*)A.row_ptr); mxFree( A.row_ptr);

    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);

    free_emxArray( (emxArray__common*)&pbmsg);
}


void crs_prodAtx_mpip1_api(const mxArray ** prhs, const mxArray **plhs) {

    emxArray_real_T      x;
    emxArray_real_T      b;
    emxArray_int32_T     nthreads;
    emxArray_real_T      pbmsg;

    struct_T             A;
    b_struct_T           comm;
    mxArray              *_sub_mx1;

    int32_T              pbsz;

    /* Marshall in function inputs */

    if ( !mxIsStruct(prhs[0]))
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument A has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[0])!=5)
        mexWarnMsgIdAndTxt("crs_prodAtx_mpip1:InputStructWrongFields",
            "Input argument A has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument A must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[0], 0, "row_ptr");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument A does not have the field row_ptr.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument A.row_ptr has incorrect data type. int32 is expected.");
    *(void**)&A.row_ptr = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.row_ptr, "A.row_ptr", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "col_ind");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument A does not have the field col_ind.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument A.col_ind has incorrect data type. int32 is expected.");
    *(void**)&A.col_ind = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.col_ind, "A.col_ind", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "val");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument A does not have the field val.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument A.val has incorrect data type. double is expected.");
    *(void**)&A.val = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)A.val, "A.val", 1);
    _sub_mx1 = mxGetField( prhs[0], 0, "nrows");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument A does not have the field nrows.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument A.nrows has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument A.nrows should be a scalar.");
    A.nrows = *(int32_T*)mxGetData(_sub_mx1);
    _sub_mx1 = mxGetField( prhs[0], 0, "ncols");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument A does not have the field ncols.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument A.ncols has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument A.ncols should be a scalar.");
    A.ncols = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument x has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)&x, "x", 2);
    plhs[0] = mxDuplicateArray( prhs[2]);
    if ( mxGetData(plhs[0]) && mxGetClassID(plhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument b has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(plhs[0], (emxArray__common *)&b, "b", 2);
    if ( mxGetData(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument nthreads has incorrect data type. int32 is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)&nthreads, "nthreads", 1);

    if ( !mxIsStruct(prhs[4]))
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument comm has incorrect data type. struct is expected.");
    if ( mxGetNumberOfFields( prhs[4])!=3)
        mexWarnMsgIdAndTxt("crs_prodAtx_mpip1:InputStructWrongFields",
            "Input argument comm has incorrect number of fields.");
    if ( mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument comm must contain 1 items.");

    _sub_mx1 = mxGetField( prhs[4], 0, "data");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field data.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument comm.data has incorrect data type. uint8 is expected.");
    *(void**)&comm.data = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.data, "comm.data", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "type");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field type.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument comm.type has incorrect data type. char is expected.");
    *(void**)&comm.type = mxCalloc(1, sizeof(emxArray__common));
    alias_mxArray_to_emxArray(_sub_mx1, (emxArray__common*)comm.type, "comm.type", 2);
    _sub_mx1 = mxGetField( prhs[4], 0, "nitems");
    if ( _sub_mx1==NULL)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputStruct",
            "Input argument comm does not have the field nitems.");
    if ( mxGetData(_sub_mx1) && mxGetClassID(_sub_mx1) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument comm.nitems has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(_sub_mx1) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument comm.nitems should be a scalar.");
    comm.nitems = *(int32_T*)mxGetData(_sub_mx1);
    if ( mxGetData(prhs[5]) && mxGetClassID(prhs[5]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument pbmsg has incorrect data type. double is expected.");
    alias_mxArray_to_emxArray(prhs[5], (emxArray__common *)&pbmsg, "pbmsg", 1);
    if ( mxGetData(prhs[6]) && mxGetClassID(prhs[6]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongInputType",
            "Input argument pbsz has incorrect data type. int32 is expected.");
    if ( mxGetNumberOfElements(prhs[6]) != 1)
        mexErrMsgIdAndTxt("crs_prodAtx_mpip1:WrongSizeOfInputArg",
            "Argument pbsz should be a scalar.");
    pbsz = *(int32_T*)mxGetData(prhs[6]);

    /* Invoke the target function */
    crs_prodAtx_initialize();
    crs_prodAtx_mpip1(&A, &x, &b, &nthreads, &comm, &pbmsg, pbsz);
    crs_prodAtx_terminate();

    /* Marshall out function outputs */
    if (b.canFreeData) plhs[2] = move_emxArray_to_mxArray((emxArray__common*)&b, mxDOUBLE_CLASS);

    /* Free temporary variables */
    free_emxArray( (emxArray__common*)A.val); mxFree( A.val);
    free_emxArray( (emxArray__common*)A.col_ind); mxFree( A.col_ind);
    free_emxArray( (emxArray__common*)A.row_ptr); mxFree( A.row_ptr);

    free_emxArray( (emxArray__common*)&x);
    free_emxArray( (emxArray__common*)&b);
    free_emxArray( (emxArray__common*)&nthreads);
    free_emxArray( (emxArray__common*)comm.type); mxFree( comm.type);
    free_emxArray( (emxArray__common*)comm.data); mxFree( comm.data);

    free_emxArray( (emxArray__common*)&pbmsg);
}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {

    if (nrhs == 4) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_prodAtx:TooManyOutputArguments","Too many output arguments for entry-point 'crs_prodAtx'.");

        /* Call the API function. */
        crs_prodAtx_api(prhs, (const mxArray**)plhs);
    }

    else if (nrhs == 2) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_prodAtx_ser:TooManyOutputArguments","Too many output arguments for entry-point 'crs_prodAtx_ser'.");

        /* Call the API function. */
        crs_prodAtx_ser_api(prhs, (const mxArray**)plhs);
    }

    else if (nrhs == 3) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_prodAtx_ser1:TooManyOutputArguments","Too many output arguments for entry-point 'crs_prodAtx_ser1'.");

        /* Call the API function. */
        crs_prodAtx_ser1_api(prhs, (const mxArray**)plhs);
    }

    else if (nrhs == 5) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_prodAtx_mpi:TooManyOutputArguments","Too many output arguments for entry-point 'crs_prodAtx_mpi'.");

        /* Call the API function. */
        crs_prodAtx_mpi_api(prhs, (const mxArray**)plhs);
    }

    else if (nrhs == 6) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_prodAtx_mpip:TooManyOutputArguments","Too many output arguments for entry-point 'crs_prodAtx_mpip'.");

        /* Call the API function. */
        crs_prodAtx_mpip_api(prhs, (const mxArray**)plhs);
    }

    else if (nrhs == 7) {
         if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_prodAtx_mpip1:TooManyOutputArguments","Too many output arguments for entry-point 'crs_prodAtx_mpip1'.");

        /* Call the API function. */
        crs_prodAtx_mpip1_api(prhs, (const mxArray**)plhs);
    }

    else
        mexErrMsgIdAndTxt("crs_prodAtx:WrongNumberOfInputs","Incorrect number of input variables for entry-point 'crs_prodAtx'.");

}

