/*
 * cudaMatCreate_mex.c
 *
 * Auxiliary code for mexFunction of cudaMatCreate
 *
 * C source code generated by m2c.
 * %#m2c options: codegenArgs=-args {int32(0), int32(0), int32(0)} cudaMatCreate_2args -args {int32(0), int32(0)}  enableInline=1
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C file generated by codegen in lib mode */
#include "cudaMatCreate.h"
#include "m2c.c"
/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

void cudaMatCreate_api(const mxArray ** prhs, const mxArray **plhs) {

    struct0_T            mat;
    mxArray              *_sub_mx1;

    int32_T              m;
    int32_T              n;
    int32_T              type;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaMatCreate:WrongInputType",
            "Input argument m has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cudaMatCreate:WrongSizeOfInputArg",
            "Argument m should be a scalar.");
    m = *(int32_T*)mxGetData(prhs[0]);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaMatCreate:WrongInputType",
            "Input argument n has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cudaMatCreate:WrongSizeOfInputArg",
            "Argument n should be a scalar.");
    n = *(int32_T*)mxGetData(prhs[1]);
    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaMatCreate:WrongInputType",
            "Input argument type has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cudaMatCreate:WrongSizeOfInputArg",
            "Argument type should be a scalar.");
    type = *(int32_T*)mxGetData(prhs[2]);

    /* Preallocate output variables */
    *(void **)&mat.type = mxCalloc(1, sizeof(emxArray__common));    init_emxArray((emxArray__common*)mat.type, 2);
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    cudaMatCreate_initialize();

    cudaMatCreate(m, n, type, &mat, errCode, toplevel);

    cudaMatCreate_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "data", "type", "dims",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 3, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, copy_scalar_to_mxArray(&mat.data, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, move_emxArray_to_mxArray((emxArray__common*)mat.type, mxINT32_CLASS));
    {int32_T _size[] = {1, 2};
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_array_to_mxArray(mat.dims, mxINT32_CLASS, 2, _size)); }
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

    /* Free temporary variables */
    free_emxArray((emxArray__common*)mat.type); mxFree(mat.type);

}
void cudaMatCreate_2args_api(const mxArray ** prhs, const mxArray **plhs) {

    struct1_T            vec;
    mxArray              *_sub_mx1;

    int32_T              m;
    int32_T              n;
    int32_T              *errCode;
    boolean_T            *toplevel;

    /* Marshall in function inputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaMatCreate_2args:WrongInputType",
            "Input argument m has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cudaMatCreate_2args:WrongSizeOfInputArg",
            "Argument m should be a scalar.");
    m = *(int32_T*)mxGetData(prhs[0]);
    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cudaMatCreate_2args:WrongInputType",
            "Input argument n has incorrect data type. int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("cudaMatCreate_2args:WrongSizeOfInputArg",
            "Argument n should be a scalar.");
    n = *(int32_T*)mxGetData(prhs[1]);

    /* Preallocate output variables */
    {mwSize l_size[] = {1, 1};
    *(void **)&errCode = prealloc_mxArray((mxArray**)&plhs[1], mxINT32_CLASS, 2, l_size); }
    {mwSize l_size[] = {1, 1};
    *(void **)&toplevel = prealloc_mxArray((mxArray**)&plhs[2], mxLOGICAL_CLASS, 2, l_size); }

    /* Invoke the target function */
    cudaMatCreate_initialize();

    cudaMatCreate_2args(m, n, &vec, errCode, toplevel);

    cudaMatCreate_terminate();

    /* Marshall out function outputs */
    {const char *_fields[] = { "data", "type", "dims",  ""};
    int32_T _one=1;
    plhs[0] = create_struct_mxArray(1, &_one, 3, _fields);}
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 0, copy_scalar_to_mxArray(&vec.data, mxUINT64_CLASS));
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 1, copy_scalar_to_mxArray(&vec.type, mxINT32_CLASS));
    {int32_T _size[] = {1, 2};
    mxSetFieldByNumber((mxArray*)(plhs[0]), 0, 2, copy_array_to_mxArray(vec.dims, mxINT32_CLASS, 2, _size)); }
    /* Nothing to do for plhs[1] */
    /* Nothing to do for plhs[2] */

}

void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 3) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("cudaMatCreate:TooManyOutputArguments","Too many output arguments for entry-point cudaMatCreate.");
        /* Call the API function. */
        cudaMatCreate_api(prhs, (const mxArray**)outputs);
    }
    else if (nrhs == 2) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("cudaMatCreate_2args:TooManyOutputArguments","Too many output arguments for entry-point cudaMatCreate_2args.");
        /* Call the API function. */
        cudaMatCreate_2args_api(prhs, (const mxArray**)outputs);
    }
    else
        mexErrMsgIdAndTxt("cudaMatCreate:WrongNumberOfInputs","Incorrect number of input variables for entry-point cudaMatCreate.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}